apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "61.9.0"
    helm:
      values: |
        grafana:
          enabled: true
          adminPassword: "admin123"
          service:
            type: ClusterIP
          persistence:
            enabled: false
          additionalDataSources:
            - name: Loki
              type: loki
              url: http://loki-gateway.observability.svc.cluster.local
              access: proxy
            - name: Tempo
              type: tempo
              url: http://tempo.observability.svc.cluster.local:3100
              access: proxy
        prometheusOperator:
          admissionWebhooks:
            enabled: false
          tls:
            enabled: false
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
            retention: 7d
            resources:
              requests:
                memory: 400Mi
                cpu: 150m
              limits:
                memory: 800Mi
                cpu: 400m
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: local-path
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 5Gi
        alertmanager:
          enabled: false
        kubeEtcd:
          enabled: false
        kubeControllerManager:
          enabled: false
        kubeScheduler:
          enabled: false
        kubeProxy:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true