apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sample-api
  namespace: observability
  labels:
    release: prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - sample-api
  selector:
    matchLabels:
      app: sample-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
